name: AI Recorder
description: A powerful tool for recording and transcribing audio, perfect for any offline meetings.
full_description: 'AI Recorder is your go-to app for capturing and transcribing audio effortlessly. Whether you’re in a doctor’s appointment, a business meeting, or any offline gathering, AI Recorder ensures you never miss a word.
Key Features:
<br/>
<br/>•	High-quality audio recording
<br/>•	Accurate transcription of audio to text
<br/>•	Automatic summary generation for quick insights
<br/>•	Works perfectly in offline environments'
android: https://telegra.ph/Replace-this-link-07-23
iOS: https://telegra.ph/Replace-this-link-07-23
web: https://telegra.ph/Replace-this-link-07-23
screenshots:
  - 1.png
  - 2.png
  - 3.png
  - 4.png
producthunt: https://telegra.ph/Replace-this-link-07-23
companies:
  - url: https://telegra.ph/Replace-this-link-07-23
    image: androidpolice.png
  - url: https://telegra.ph/Replace-this-link-07-23
    image: producthunt.png
